# Generated by Django 5.2.15 on 2026-06-30 09:18

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormatOfPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceOfPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('associated_country', models.CharField(blank=True, max_length=1000, null=True)),
                ('viaf', models.CharField(blank=True, max_length=1000, null=True, verbose_name='VIAF')),
                ('other_links', models.TextField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='agents', to='researchdata.agentrole')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='researchdata.gender')),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('role__name'), django.db.models.functions.text.Upper('name'), 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrimarySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('year_of_publication', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primarysources_authors', to='researchdata.agent')),
                ('languages', models.ManyToManyField(blank=True, related_name='primarysources', to='researchdata.language')),
                ('other_contributors', models.ManyToManyField(blank=True, related_name='primarysources_othercontributors', to='researchdata.agent')),
                ('place_of_publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primarysources', to='researchdata.placeofpublication')),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecondarySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('year_of_publication', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondarysources_authors', to='researchdata.agent')),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('false_imprint', models.CharField(blank=True, max_length=1000, null=True)),
                ('specific_location', models.CharField(blank=True, max_length=1000, null=True)),
                ('year_of_publication', models.IntegerField(blank=True, null=True)),
                ('specific_date', models.CharField(blank=True, max_length=1000, null=True)),
                ('lost_book', models.BooleanField(default=False)),
                ('multilingual', models.BooleanField(default=False)),
                ('translation', models.TextField(blank=True, null=True)),
                ('number_of_issues', models.IntegerField(blank=True, null=True)),
                ('pagination', models.CharField(blank=True, max_length=1000, null=True)),
                ('number_of_main_text_pages', models.IntegerField(blank=True, null=True)),
                ('number_of_liminary_pages', models.IntegerField(blank=True, null=True)),
                ('number_of_pages_containing_french', models.IntegerField(blank=True, null=True)),
                ('illustrations', models.BooleanField(default=False)),
                ('stc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='STC/Wing number')),
                ('estc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ESTC')),
                ('ustc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='USTC')),
                ('fb_number', models.CharField(blank=True, max_length=1000, null=True, verbose_name='FB number')),
                ('rccc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Renaissance Cultural Crossroads Catalogue (RCCC)')),
                ('full_text_image', models.CharField(blank=True, max_length=1000, null=True, verbose_name='full-text - image')),
                ('full_text_transcription', models.CharField(blank=True, max_length=1000, null=True, verbose_name='full-text - transcription')),
                ('number_of_surviving_copies_in_uk', models.IntegerField(blank=True, null=True, verbose_name='Number of surviving copies in UK and Ireland')),
                ('number_of_surviving_copies_in_rest_of_world', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('record_date_created', models.DateTimeField(auto_now_add=True)),
                ('record_date_updated', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts_authors', to='researchdata.agent')),
                ('format_of_publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts', to='researchdata.formatofpublication')),
                ('languages', models.ManyToManyField(blank=True, to='researchdata.language')),
                ('other_contributors', models.ManyToManyField(blank=True, related_name='texts_othercontributors', to='researchdata.agent')),
                ('place_of_publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts', to='researchdata.placeofpublication')),
                ('primary_sources', models.ManyToManyField(blank=True, related_name='texts', to='researchdata.primarysource')),
                ('publisher', models.ManyToManyField(blank=True, related_name='texts_publishers', to='researchdata.agent', verbose_name='printer/publisher')),
                ('secondary_sources', models.ManyToManyField(blank=True, related_name='texts', to='researchdata.secondarysource')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts', to='researchdata.subject')),
                ('translator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts_translator', to='researchdata.agent')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts', to='researchdata.texttype')),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('title'), 'id'],
            },
        ),
    ]
