# Generated by Django 5.2.16 on 2026-07-30 10:47

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_researchdata_agentrole_name')],
            },
        ),
        migrations.CreateModel(
            name='FormatOfPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_researchdata_formatofpublication_name')],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_researchdata_gender_name')],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_researchdata_language_name')],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('birth_year', models.CharField(blank=True, max_length=1000, null=True)),
                ('death_year', models.CharField(blank=True, max_length=1000, null=True)),
                ('viaf', models.CharField(blank=True, max_length=1000, null=True, verbose_name='VIAF')),
                ('other_links', models.TextField(blank=True, null=True)),
                ('roles', models.ManyToManyField(blank=True, related_name='agents', to='researchdata.agentrole')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='researchdata.gender')),
                ('associated_countries', models.ManyToManyField(blank=True, related_name='agents', to='researchdata.place')),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_researchdata_placetype_name')],
            },
        ),
        migrations.AddField(
            model_name='place',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='places', to='researchdata.placetype'),
        ),
        migrations.CreateModel(
            name='Relationships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_researchdata_relationships_name')],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_researchdata_subject_name')],
            },
        ),
        migrations.CreateModel(
            name='TextType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_researchdata_texttype_name')],
            },
        ),
        migrations.CreateModel(
            name='TextualFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_researchdata_textualfeatures_name')],
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ESTC')),
                ('stc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='STC/Wing')),
                ('ustc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='USTC')),
                ('title', models.TextField()),
                ('imprint', models.TextField(blank=True, null=True)),
                ('false_imprint', models.BooleanField(default=False)),
                ('year_of_publication', models.CharField(blank=True, max_length=1000, null=True)),
                ('associated_date', models.CharField(blank=True, max_length=1000, null=True)),
                ('lost_book', models.BooleanField(default=False)),
                ('number_of_languages', models.IntegerField(blank=True, null=True)),
                ('number_of_issues', models.IntegerField(blank=True, null=True)),
                ('pagination', models.CharField(blank=True, max_length=1000, null=True)),
                ('number_of_pages_containing_french', models.IntegerField(blank=True, null=True, verbose_name='Number of pages containing French')),
                ('fb', models.CharField(blank=True, max_length=1000, null=True, verbose_name='FB')),
                ('rccc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='RCCC')),
                ('nelson_and_seccombe', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nelson and Seccombe')),
                ('stationers_register', models.CharField(blank=True, max_length=1000, null=True, verbose_name="stationers' register")),
                ('plre', models.CharField(blank=True, max_length=1000, null=True, verbose_name='PLRE')),
                ('full_text_image', models.CharField(blank=True, max_length=1000, null=True, verbose_name='full-text - image')),
                ('full_text_transcription', models.CharField(blank=True, max_length=1000, null=True, verbose_name='full-text - transcription')),
                ('number_of_surviving_copies_in_uk', models.IntegerField(blank=True, null=True, verbose_name='Number of surviving copies in UK and Ireland')),
                ('number_of_surviving_copies_in_continental_europe', models.IntegerField(blank=True, null=True, verbose_name='Number of Surviving Copies in Continental Europe')),
                ('number_of_surviving_copies_in_rest_of_world', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('record_date_created', models.DateTimeField(auto_now_add=True)),
                ('record_date_updated', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
                ('associated_locations', models.ManyToManyField(blank=True, to='researchdata.place')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts_authors', to='researchdata.agent')),
                ('dedicatees', models.ManyToManyField(blank=True, related_name='texts_dedicatees', to='researchdata.agent')),
                ('format_of_publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts', to='researchdata.formatofpublication')),
                ('languages', models.ManyToManyField(blank=True, to='researchdata.language')),
                ('other_contributors', models.ManyToManyField(blank=True, related_name='texts_othercontributors', to='researchdata.agent')),
                ('owners', models.ManyToManyField(blank=True, related_name='texts_owners', to='researchdata.agent')),
                ('place_of_publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts', to='researchdata.place')),
                ('publishers', models.ManyToManyField(blank=True, related_name='texts_publishers', to='researchdata.agent', verbose_name='printer/publisher')),
                ('relationships', models.ManyToManyField(blank=True, related_name='texts', to='researchdata.relationships')),
                ('subjects', models.ManyToManyField(blank=True, related_name='texts', to='researchdata.subject')),
                ('translators', models.ManyToManyField(blank=True, related_name='texts_translators', to='researchdata.agent')),
                ('text_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts', to='researchdata.texttype', verbose_name='type')),
                ('textual_features', models.ManyToManyField(blank=True, related_name='texts_dedicatees', to='researchdata.textualfeatures')),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('title'), 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_researchdata_place_name'),
        ),
    ]
