# Generated by Django 5.2.15 on 2026-07-12 20:27

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_researchdata_agentrole_name')],
            },
        ),
        migrations.CreateModel(
            name='FormatOfPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_researchdata_formatofpublication_name')],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_researchdata_gender_name')],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('birth_year', models.CharField(blank=True, max_length=1000, null=True)),
                ('death_year', models.CharField(blank=True, max_length=1000, null=True)),
                ('associated_country', models.CharField(blank=True, max_length=1000, null=True)),
                ('viaf', models.CharField(blank=True, max_length=1000, null=True, verbose_name='VIAF')),
                ('other_links', models.TextField(blank=True, null=True)),
                ('roles', models.ManyToManyField(blank=True, related_name='agents', to='researchdata.agentrole')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='researchdata.gender')),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_researchdata_language_name')],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_researchdata_place_name')],
            },
        ),
        migrations.CreateModel(
            name='PrimarySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='title')),
                ('year_of_publication', models.CharField(blank=True, max_length=1000, null=True)),
                ('manuscript', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primarysources_authors', to='researchdata.agent')),
                ('languages', models.ManyToManyField(blank=True, related_name='primarysources', to='researchdata.language')),
                ('other_contributors', models.ManyToManyField(blank=True, related_name='primarysources_othercontributors', to='researchdata.agent')),
                ('place_of_publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primarysources', to='researchdata.place')),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecondarySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='title')),
                ('year_of_publication', models.CharField(blank=True, max_length=1000, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondarysources_authors', to='researchdata.agent')),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_researchdata_subject_name')],
            },
        ),
        migrations.CreateModel(
            name='TextType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_researchdata_texttype_name')],
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('false_imprint', models.BooleanField(default=False)),
                ('address_of_publication', models.TextField(blank=True, null=True)),
                ('associated_location', models.CharField(blank=True, max_length=1000, null=True)),
                ('year_of_publication', models.IntegerField(blank=True, null=True)),
                ('specific_date', models.CharField(blank=True, max_length=1000, null=True)),
                ('lost_book', models.BooleanField(default=False)),
                ('multilingual', models.BooleanField(default=False)),
                ('translation', models.BooleanField(default=False)),
                ('number_of_issues', models.IntegerField(blank=True, null=True)),
                ('pagination', models.CharField(blank=True, max_length=1000, null=True)),
                ('number_of_main_text_pages', models.IntegerField(blank=True, null=True)),
                ('number_of_liminary_pages', models.IntegerField(blank=True, null=True)),
                ('number_of_pages_containing_french', models.IntegerField(blank=True, null=True, verbose_name='Number of pages containing French')),
                ('nelson_and_seccombe', models.TextField(blank=True, null=True, verbose_name='Nelson and Seccombe')),
                ('plre', models.TextField(blank=True, null=True, verbose_name='PLRE')),
                ('illustrations', models.BooleanField(default=False)),
                ('stc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='STC/Wing number')),
                ('estc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ESTC')),
                ('ustc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='USTC')),
                ('fb_number', models.CharField(blank=True, max_length=1000, null=True, verbose_name='FB number')),
                ('rccc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Renaissance Cultural Crossroads Catalogue (RCCC)')),
                ('full_text_image', models.CharField(blank=True, max_length=1000, null=True, verbose_name='full-text - image')),
                ('full_text_transcription', models.TextField(blank=True, null=True, verbose_name='full-text - transcription')),
                ('number_of_surviving_copies_in_uk', models.IntegerField(blank=True, null=True, verbose_name='Number of surviving copies in UK and Ireland')),
                ('number_of_surviving_copies_in_continental_europe', models.IntegerField(blank=True, null=True, verbose_name='Number of Surviving Copies in Continental Europe')),
                ('number_of_surviving_copies_in_rest_of_world', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('record_date_created', models.DateTimeField(auto_now_add=True)),
                ('record_date_updated', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts_authors', to='researchdata.agent')),
                ('dedicatee', models.ManyToManyField(blank=True, related_name='texts_dedicatees', to='researchdata.agent')),
                ('format_of_publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts', to='researchdata.formatofpublication')),
                ('languages', models.ManyToManyField(blank=True, to='researchdata.language')),
                ('other_contributors', models.ManyToManyField(blank=True, related_name='texts_othercontributors', to='researchdata.agent')),
                ('owner', models.ManyToManyField(blank=True, related_name='texts_owners', to='researchdata.agent')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts', to='researchdata.place')),
                ('primary_sources', models.ManyToManyField(blank=True, related_name='texts', to='researchdata.primarysource')),
                ('publisher', models.ManyToManyField(blank=True, related_name='texts_publishers', to='researchdata.agent', verbose_name='printer/publisher')),
                ('secondary_sources', models.ManyToManyField(blank=True, related_name='texts', to='researchdata.secondarysource')),
                ('subject', models.ManyToManyField(blank=True, related_name='texts', to='researchdata.subject')),
                ('translator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts_translator', to='researchdata.agent')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts', to='researchdata.texttype')),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('title'), 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='primarysource',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_researchdata_primarysource_name'),
        ),
        migrations.AddConstraint(
            model_name='secondarysource',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('name'), name='unique_researchdata_secondarysource_name'),
        ),
    ]
